[2023-07-17T23:35:18.345+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.make_figures.plot_all_together manual__2023-07-17T23:20:56.537598+00:00 [queued]>
[2023-07-17T23:35:18.357+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.make_figures.plot_all_together manual__2023-07-17T23:20:56.537598+00:00 [queued]>
[2023-07-17T23:35:18.357+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-17T23:35:18.378+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): make_figures.plot_all_together> on 2023-07-17 23:20:56.537598+00:00
[2023-07-17T23:35:18.386+0000] {standard_task_runner.py:57} INFO - Started process 2147 to run task
[2023-07-17T23:35:18.389+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'make_figures.plot_all_together', 'manual__2023-07-17T23:20:56.537598+00:00', '--job-id', '873', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpansuqa_p']
[2023-07-17T23:35:18.390+0000] {standard_task_runner.py:85} INFO - Job 873: Subtask make_figures.plot_all_together
[2023-07-17T23:35:18.474+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.make_figures.plot_all_together manual__2023-07-17T23:20:56.537598+00:00 [running]> on host ac2d7d5a0887
[2023-07-17T23:35:18.594+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='make_figures.plot_all_together' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T23:20:56.537598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-17T23:20:56.537598+00:00'
[2023-07-17T23:37:39.656+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-17T23:37:39.824+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 2147. PIDs of all processes in the group: [2147]
[2023-07-17T23:37:39.825+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2147
[2023-07-17T23:37:39.826+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-17T23:37:39.848+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_dag.py", line 180, in all_together_figure
    color_betweenness = list(dict(nx.betweenness_centrality(graph)).values())
  File "<class 'networkx.utils.decorators.argmap'> compilation 18", line 5, in argmap_betweenness_centrality_14
    import warnings
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/algorithms/centrality/betweenness.py", line 129, in betweenness_centrality
    S, P, sigma, _ = _single_source_shortest_path_basic(G, s)
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/algorithms/centrality/betweenness.py", line 274, in _single_source_shortest_path_basic
    P[w].append(v)  # predecessors
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-17T23:37:39.855+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=make_figures.plot_all_together, execution_date=20230717T232056, start_date=20230717T233518, end_date=20230717T233739
[2023-07-17T23:37:40.994+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 873 for task make_figures.plot_all_together (Task received SIGTERM signal; 2147)
[2023-07-17T23:37:41.054+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2147, status='terminated', exitcode=1, started='23:35:17') (2147) terminated with exit code 1
[2023-07-17T23:37:41.059+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2023-07-17T23:37:41.143+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
