[2023-07-17T23:35:18.363+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.make_figures.plot_k_core_shell manual__2023-07-17T23:20:56.537598+00:00 [queued]>
[2023-07-17T23:35:18.374+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.make_figures.plot_k_core_shell manual__2023-07-17T23:20:56.537598+00:00 [queued]>
[2023-07-17T23:35:18.375+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-17T23:35:18.396+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): make_figures.plot_k_core_shell> on 2023-07-17 23:20:56.537598+00:00
[2023-07-17T23:35:18.418+0000] {standard_task_runner.py:57} INFO - Started process 2148 to run task
[2023-07-17T23:35:18.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'make_figures.plot_k_core_shell', 'manual__2023-07-17T23:20:56.537598+00:00', '--job-id', '875', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp5lp9wgj0']
[2023-07-17T23:35:18.425+0000] {standard_task_runner.py:85} INFO - Job 875: Subtask make_figures.plot_k_core_shell
[2023-07-17T23:35:18.482+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.make_figures.plot_k_core_shell manual__2023-07-17T23:20:56.537598+00:00 [running]> on host ac2d7d5a0887
[2023-07-17T23:35:18.600+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='make_figures.plot_k_core_shell' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T23:20:56.537598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-17T23:20:56.537598+00:00'
[2023-07-17T23:37:39.659+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-17T23:37:39.802+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 2148. PIDs of all processes in the group: [2148]
[2023-07-17T23:37:39.808+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2148
[2023-07-17T23:37:39.809+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-17T23:37:39.956+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_dag.py", line 326, in k_core_shell_figure
    plt.savefig("figures/k-core_sociopatterns.png", dpi=600)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 977, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2325, in print_figure
    **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/figure.py", line 2846, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3092, in draw
    renderer, self, artists, self.figure.suppressComposite)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/patches.py", line 4502, in draw
    self._facecolor if f and self._facecolor[3] else None)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 170, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-17T23:37:39.966+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=make_figures.plot_k_core_shell, execution_date=20230717T232056, start_date=20230717T233518, end_date=20230717T233739
[2023-07-17T23:37:41.005+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 875 for task make_figures.plot_k_core_shell (Task received SIGTERM signal; 2148)
[2023-07-17T23:37:41.117+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2148, status='terminated', exitcode=1, started='23:35:17') (2148) terminated with exit code 1
[2023-07-17T23:37:41.122+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2023-07-17T23:37:41.216+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
